import "./globals.css";

// BOOTSTRAP
import "bootstrap/dist/css/bootstrap.min.css"
import 'bootstrap-icons/font/bootstrap-icons.css';

// COMPONENTES
import Navbar from "@/components/blocks/Navbar";

// Fonte padrão da GM
import { Overpass } from "next/font/google";
const overpass = Overpass({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});


export const metadata = {
  title: "Gerenciador de Treinamentos",
  icons: {
    icon: "/img/General_Motors.svg", // pode ser qualquer nome
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${overpass.className} d-flex flex-column flex-lg-row gap-3`}>
        {/* CSS do fa icons */}
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet" />

        {/* Barra de navegação */}
        <Navbar />

        {/* Corpo da página */}
        <div className="flex-grow-1">
          {children}
        </div>

        {/* script do BOOTSTRAP */}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}
