-- Criando o Bando de dados CONTROLE_TREINAMENTOS
CREATE DATABASE if not exists CONTROLE_TREINAMENTOS;
USE CONTROLE_TREINAMENTOS;


-- DROP DATABASE IF EXISTS ControleTreinamento;


/*
CRIAR E ATRIBUIR PERMISSÃO A USUÁRIO
	create user USUARIO identified by 'ABC123xyz';	-- Cria USUARIO
	grant PROCEDIMENTO on BANCO.TABELA to USUARIO	-- Permite que o USUARIO realize o PROCEDIMENTO na TABELA do BANCO
*/
